# Generated by Django 3.2.4 on 2021-06-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MinuteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='item',
        ),
        migrations.RemoveField(
            model_name='minutes',
            name='item',
        ),
        migrations.AddField(
            model_name='agenda',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.agendaitems'),
        ),
        migrations.AddField(
            model_name='minutes',
            name='minutes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.minuteitems'),
        ),
    ]
