# Generated by Django 3.2.4 on 2021-06-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room', '0006_auto_20210617_1352'),
        ('core', '0002_auto_20210617_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgendaItems',
            new_name='AgendaItem',
        ),
        migrations.RenameModel(
            old_name='Minutes',
            new_name='Minute',
        ),
        migrations.RenameModel(
            old_name='MinuteItems',
            new_name='MinuteItem',
        ),
    ]
