# Generated by Django 3.2.4 on 2021-06-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210617_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.agenda'),
        ),
        migrations.AlterField(
            model_name='minuteitem',
            name='minute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.minute'),
        ),
    ]
