# Generated by Django 3.2.4 on 2021-06-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_alter_documentchatmessage_annotation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentchatmessage',
            old_name='annotation_id',
            new_name='annotationId',
        ),
    ]
