# Generated by Django 3.2.4 on 2021-06-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_documentchat_file'),
        ('meeting_room', '0002_alter_meetingchatroom_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingchatroom',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='Documents uploaded in this meeting.', related_name='meetings_added', to='document.DocumentChat'),
        ),
    ]
