# Generated by Django 3.2.4 on 2021-06-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('meeting_room', '0003_meetingchatroom_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingchatroom',
            name='agenda',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.agenda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingchatroom',
            name='minutes',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.minutes'),
            preserve_default=False,
        ),
    ]
