# Generated by Django 3.2.4 on 2021-06-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210617_1344'),
        ('meeting_room', '0005_auto_20210617_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingchatroom',
            name='agenda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.agenda'),
        ),
        migrations.AlterField(
            model_name='meetingchatroom',
            name='minutes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.minutes'),
        ),
    ]
